language: java

env:
  global:
    - CC_TEST_REPORTER_ID=${CC_TEST_REPORTER_ID}
    - M2_HOME=${HOME}/apache-maven-3.5.0 PATH=${M2_HOME}/bin:${PATH}

cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/apache-maven-3.5.0"

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

before_install:
  - if [ ! -d "${M2_HOME}"/bin ]; then curl https://archive.apache.org/dist/maven/maven-3/3.5.0/binaries/apache-maven-3.5.0-bin.tar.gz | tar zxf - -C "${HOME}"; fi

install:
  - mvn install -T 2.0C -DrepoToken=${repoToken}

after_script:
  - mvn clean -T 2.0C cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:report
